# Compiler and flags
CC = gcc
CFLAGS = -Wall -g

# The final executable name
TARGET = stage1exe

# All the .c files that need to be compiled
SRCS = driver.c lexer_new.c parser.c

# Rule to build the final executable
all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

# Rule to clean up the compiled files
clean:
	rm -f $(TARGET) cleanOutput.txt